version: '2'
services:
  nginx:
    build:
      context: nginx-image
    links:
      - letsencrypt
      - app
    environment:
      - MY_DOMAIN_NAME=www.ittysensor.com
    mem_limit: 1g
    cpu_shares: 256
    # restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes_from:
      - letsencrypt

  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    command: ["certonly",
    "--standalone",
    "-d", "www.ittysensor.com",
    "--text",
    "--agree-tos",
    "--email", "ittysensor@gmail.com",
    "--rsa-key-size",  "4096",
    "--verbose",
    "--renew-by-default",
    "--standalone-supported-challenges", "http-01"  ]
    volumes:
      - /etc/letsencrypt
      - /var/lib/letsencrypt
    expose:
      - "80"
  app:
    image: mitchelljthomas/medir:latest
    expose:
      - "80"
      - "433"
