version: 2.1
jobs:
 build:
   docker:
     - image: circleci/golang:latest-node
   steps:
     - run:
         name: The First Step
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
     - run:
         name: Node Version
         command: |
           node -v
     - run:
         name: Go Vesion
         command: |
           go version
