---
version: 2
jobs:

  UI-Build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Node Version
          command: |
            node -v
      - run:
          name: Yarn it
          command: |
            cd ui/medir-ui
            yarn install
            yarn build

  Webserver-Build:
    docker:
      - image: circleci/golang:latest-
    working_directory: /go/src/github.com/mitchelljthomas/medir-portal/web-portal
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.3-ce
      - run: |
          TAG=0.2.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t mitchelljthomas/medir-portal:$TAG .
          docker push mitchelljthomas/medir-portal:$TAG


workflows:
  version: 2
  Medir_Portal:
    jobs:
      - UI-Build
      - Webserver-Build:
          requires:
            - UI-Build
