version: 2.1
jobs:
  Version-Check:
    docker:
      - image: circleci/golang:latest-node
    steps:
     - run:
         name: Linux Version
         command: |
           echo 'Hello World!'
           cat /etc/*-release
     - run:
         name: Node Version
         command: |
           node -v
     - run:
         name: Go Vesion
         command: |
           go version
           Now-Complete:
  I-Have-Code:
   docker:
     - image: alpine:latest
   steps:
     - checkout
     - run:
         name: Code Has Arrived
         command: |
           ls -al
           echo '^^^That should look familiar^^^'
  UI-Build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Yarn it
          command: |
            cd ui/medir-ui
            yarn
      - run:
          name: Yarn Audit
          command: |
            cd ui/medir-ui
            yarn audit
  Webserver-Build:
    docker:
      -image circleci/go:latest
    steps:
      -run:
        name: Get deps
        command: |
          cd web-portal
          go get -u github.com/golang/dep/cmd/dep
          dep init
          go build -o medir-portal-server .
  Now-Complete:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: Approval Complete
         command: |
           echo 'Do work once the approval has completed'

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - Version-Check
      - I-Have-Code
      - UI-Build:
          type: approval
          requires:
            - I-Have-Code
     - Webserver-Build:
          requires:
            - I-Have-Code
     - Hold-For-Approval:
         type: approval
         requires:
           - UI-Build
           - Webserver-Build
     - Now-Complete:
         requires:
           - Hold-For-Approval
