---
version: 2
jobs:

  UI-Build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Node Version
          command: |
            node -v
      - run:
          name: Yarn it
          working_directory: ui/medir-ui
          command: |
            yarn install
            yarn build
      - persist_to_workspace:
          root: .
          paths:
            - ui/medir-ui/build/

  Webserver-Build:
    docker:
      - image: circleci/node:latest
    working_directory:  web-portal
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: build
      - run:
          name: Remote build of webserver
          command: |
            TAG=0.2.$CIRCLE_BUILD_NUM
            ls build
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            echo "Building medir-portal:$TAG"
            docker build -t mitchelljthomas/medir-portal:$TAG .
            docker push mitchelljthomas/medir-portal:$TAG


workflows:
  version: 2
  Medir_Portal:
    jobs:
      - UI-Build
      - Webserver-Build:
          requires:
            - UI-Build
