---
version: 2
jobs:
  UI-Build:
    docker:
      - image: circleci/node:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Node Version
          command: |
            node -v
      - run:
          name: Yarn it
          working_directory: ui/medir-ui
          command: |
            yarn install
            yarn audit --level moderate
            yarn build
      - run:
          working_directory:  web-portal
          name: Remote build of webserver
          command: |
            mv ../ui/medir-ui/build/ ./build/
            TAG=$CIRCLE_BUILD_NUM-$CIRCLE_BRANCH-$CIRCLE_SHA1
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            echo "Building medir-portal:$TAG"
            docker build -t mitchelljthomas/medir-portal:$TAG .
            docker push mitchelljthomas/medir-portal:$TAG


workflows:
  version: 2
  Medir_Portal:
    jobs:
      - UI-Build
