---
version: 2.1
jobs:
  Version-Check:
    docker:
      - image: circleci/golang:latest-node
    steps:
      - run:
          name: Linux Version
          command: |
            echo 'Linux!'
            cat /etc/*-release
      - run:
          name: Node Version
          command: |
            node -v
      - run:
          name: Go Version
          command: |
            go version
  UI-Build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Yarn it
          command: |
            cd ui/medir-ui
            yarn build
  Webserver-Build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Get deps
          command: |
            cd web-portal
            go get -u github.com/golang/dep/cmd/dep
            dep init
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - UI-Build
      - Webserver-Build:
          requires:
            - UI-Build
      - Hold-For-Approval:
          type: approval
          requires:
            - UI-Build
            - Webserver-Build
      - Now-Complete:
          requires:
            - Hold-For-Approval
