version: 2.1
jobs:
 build:
   docker:
     - image: circleci/golang:latest-node
   steps:
     - run:
         name: Linux Version
         command: |
           echo 'Hello World!'
           cat /etc/*-release
     - run:
         name: Node Version
         command: |
           node -v
     - run:
         name: Go Vesion
         command: |
           go version
