version: '3'
services:
  medir-portal:
    build: .
    image: mitchelljthomas/medirportal_go:latest
    environment:
      ACME_SERVER_URL: "https://pebble:14000/directory"
    volumes:
      - ./datum:/medir/datum
      - ./certs:/medir/certs
    ports:
      - "9080:80"
      - "9443:443"
  pebble:
    build:
      dockerfile: Dockerfile-pebble
      context: .
    image: pebble:latest
