# -*- mode: restclient; -*-
###
### The following is a set of InfluxDB API REST URLS relevant to the medir database (and the unfortunately named medir measurement)
###
:influx-admin-auth := (format "Basic %s" (base64-encode-string (format "%s:%s" "bigcheeze" "tomeasure!47")))
:influx-importer-auth := (format "Basic %s" (base64-encode-string (format "%s:%s" "medir_import_user" "ittysensor@47")))
:influx-reader-auth := (format "Basic %s" (base64-encode-string (format "%s:%s" "medir_reader_user" "2016reader0916")))
:influx-rest-host := "127.0.0.1:8086"

# Authorization: :influx-auth
#
GET http://:influx-rest-host/query?q=select+count(tempc)+from+medir+where+time+%3E%3D+'2016-10-01'+group+by+device_id%2C+time(1d)&db=medir
Authorization: :influx-reader-auth
Accept: application/json
#

#
GET http://:influx-rest-host/query?q=SHOW+MEASUREMENTS&db=medir
Authorization: :influx-reader-auth
Accept: application/json
#

#
GET http://:influx-rest-host/query?q=SHOW+USERS&db=medir
Authorization: :influx-admin-auth
Accept: application/json
#

#
GET http://:influx-rest-host/query?q=SHOW+DATABASES
Authorization: :influx-admin-auth
Accept: application/json
#
