# -*- mode: restclient; -*-
###
### The following is a simulation of the Particle Webhook call
###
:webhook-host := "localhost:8080"

# Simulate posting data from Particle
POST http://:webhook-host/write?db=medir
Content-Type: application/x-www-form-urlencoded
event=dat&data={"h":44.44 "t":19.50,"ts":1474743660}&published_at=2016-09-24T19:00:46.286Z&coreid=220039000647343232363230
#
# 

# Simulate posting data from Particle
POST http://:webhook-host/write?db=medir
Content-Type: application/x-www-form-urlencoded
event=dat&data={"t":19.50,"ts":1474743649,"n":"attic"}&published_at=2016-09-24T19:00:46.286Z&coreid=220039000647343232363230
event=dat&data={"t":19.55,"h":56.79,"n":"carboy","ts":1474743650}&published_at=2016-09-24T19:00:46.288Z&coreid=220039000647343232363231
event=dat&data={"t":20.01,"h":34.0,"ts":1474743651}&published_at=2016-09-24T19:00:46.288Z&coreid=220039000647343232363232
#
# 

# Simulate posting data from Particle (secure!)
POST https://:webhook-host/write?db=medir
Content-Type: application/x-www-form-urlencoded
event=dat&data={"t":19.50,"h":56.78,"ts":1474743649}&published_at=2016-09-24T19:00:46.286Z&coreid=220039000647343232363230
#

# Simulate posting a failure code from Particle
POST http://:webhook-host/write?db=medir
Content-Type: application/x-www-form-urlencoded
event=dat&data={"fc":3,"ts":1474743001}&published_at=2016-09-24T19:00:46.286Z&coreid=220039000647343232363230
#


